FROM python:3.6

RUN apt-get update && apt-get install -y python3-dev build-essential wkhtmltopdf

WORKDIR /apiserver

COPY telegram_notifications/ .

RUN pip install --no-cache-dir --ignore-installed six -r requirements.txt

CMD [ "python", "./api.py" ]