---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    labels:
        app: apiserver
spec:
    replicas: 1
    selector:
        matchLabels:
            app: apiserver
    template:
        metadata:
            labels:
                app: apiserver
        spec:
            containers:
            - name: apiserver
              image: tradecalls/api:v
              ports:
                - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: api-service
spec:
    selector:
        app: apiserver
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000